Repository arrecadar/api, pull requests merged in 2018-05, with the labels that each got.

#12 campaign: add resources
  CHANGELOG.md
  app/Campaigns/controller.js
  app/Campaigns/index.js
  app/Campaigns/model.js
  app/Campaigns/repository.js
  app/Campaigns/request.js
  app/Campaigns/routes.js
  app/Routes.js
Labels: enhancement

#24 transformers: refactor transformers
  CHANGELOG.md
  app/Organizations/repository.js
  app/Transformers/paginate.js
Labels: enhancement

#22 authenticate: add auth flow
  .env.example
  CHANGELOG.md
  app/Routes.js
  bootstrap/app.js
  bootstrap/authenticate.js
  config/app.js
  package.json
  yarn.lock
Labels: enhancement, wip

#35 Fix development environment
  Dockerfile
  bootstrap/authenticate.js
Labels: bug
